# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:56
from __future__ import unicode_literals

import django.utils.timezone
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('labs.common', '0001_initial'),
        ('labs.common', '0002_auto_20160307_0841'),
        ('labs.common', '0003_auto_20160307_0937'),
        ('labs.common', '0004_auto_20160307_0940'),
        ('labs.common', '0005_auto_20160307_1448'),
        ('labs.common', '0006_auto_20160308_0959')
    ]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20))
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('ticket_number', models.IntegerField(blank=True, null=True)),
                ('seat_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.PositiveIntegerField(default=20)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='common.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(default=1)),
                ('online', models.BooleanField(max_length=1)),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='common.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='common.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='attendees', through='common.Registration', to='common.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('member', 'event')]),
        ),
    ]
