# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.fields.jsonb import JSONField

from labs.common.validators import (location_schema_validator,
                                    info_schema_validator,
                                    skills_schema_validator)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_squashed_0006_auto_20160308_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='locations',
            field=ArrayField(base_field=ArrayField(
                base_field=models.FloatField(default=0.0), size=2),
                blank=True, null=True,
                default=list, size=None,
                validators=[location_schema_validator]
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='info',
            field=JSONField(
                default=dict,
                blank=True, null=True,
                validators=[info_schema_validator]
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True, null=True,
                default=list, size=None,
                validators=[skills_schema_validator]
            ),
        ),
    ]
