# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 19:24
from __future__ import unicode_literals

from django.db import migrations
import django.contrib.postgres.fields.hstore
# from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20160310_0748'),
    ]

    operations = [
        # HStoreExtension(), # Db user must be superuser to create this
        # extension. It's replaced with the management command
        # `add_hstore_extension`, run: python manage.py add_hstore_extension
        migrations.AddField(
            model_name='member',
            name='contact',
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, default=dict, null=True),
        ),
    ]
