# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 19:24
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.fields import hstore
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20160310_0748'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='member',
            name='contact',
            field=hstore.HStoreField(blank=True, null=True),
        ),
    ]
