# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_member_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
