# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('labs', '0001_initial'), ('labs', '0002_auto_20160307_0841'), ('labs', '0003_auto_20160307_0937'), ('labs', '0004_auto_20160307_0940'), ('labs', '0005_auto_20160307_1448'), ('labs', '0006_auto_20160308_0959')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.PositiveIntegerField(default=20)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='labs.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(default=1)),
                ('online', models.BooleanField(max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='labs.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='labs.Member')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='attendees', through='labs.Registration', to='labs.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('member', 'event')]),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
