# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20160307_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_expected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
