# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_auto_20160307_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='created_at',
            new_name='registered_on',
        ),
    ]
